### ISSUE TITLE
Motif size

### ISSUE THREAD

**Issue by hchetia** [Illumina/ExpansionHunterDenovo#40]
Hi,
Is there limit on the maximum motif size that EHDN can detect repeats for?
The EHDN runs for all my samples (250*2 bp PE WGS data) saw a maximum of 20 based motifs. If there is, then can I increase this limit ?
Best,
Hasna

**Comment by egor-dolzhenko** [comment]
Hi Hasna,

Thank you for the question. The longest motif size can be adjusted with "max-unit-len" parameter of the "ExpansionHunterDenovo profile" command.

However, note that motif predictions are more accurate for shorter motif sizes. In my opinion, 20bp is a reasonable cutoff to use even for 2x250bp data.

Best wishes,
Egor

**Comment by hchetia** [comment]
Thanks Egor.
I have been using the Annovar based annotation for my locus results which has been very helpful. Is there a way to annotate the motif results in a similar way?
Best
Hasna

**Comment by egor-dolzhenko** [comment]
Hi Hasna,

Unfortunately we can't annotate motif analysis results the same way we annotate locus results. This is because motif analysis measures the overall enrichment of the genome with very long repeats with the given motif. In general, we can't associate motif results with a specific genomic region and so can't annotate them.

In the future versions of EHdn, we could consider extending the motif analysis as follows: For every expanded motif, generate a list of possible repeats with that motif that could have expanded, and then annotate all repeats in that list.

Best wishes,
Egor

**Comment by hchetia** [comment]
Thanks Egor.
